package util.hasher

/**
 * Object intended for disposable keys list generation.
 * 
 * Disposable keys are generated by providing a secret as a seed,
 * it is intended to be a 'lazy' IBA replacement.
 */

object HMACKeyGen {
	//TODO : actually implement this ;-)
}